# CAR_RENTAL_COMPANY_CAR
## CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS

# CAR_RENTAL_COMPANY_RENTAL_HISTORY
## HISTORY_ID, CAR_ID, START_DATE, END_DATE

# CAR_RENTAL_COMPANY_DISCOUNT_PLAN
## PLAN_ID, CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE

# 대여가 불가능한 차 지정
WITH NOT_AVAILABLE_CAR AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (START_DATE <= "2022-11-30") AND (END_DATE >= "2022-11-01")
),

# 대여가 가능한 차 추출
AVAILABLE_CAR AS (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE (CAR_ID NOT IN (SELECT CAR_ID FROM NOT_AVAILABLE_CAR)) AND
    (CAR_TYPE IN ("세단", "SUV"))
),

# 할인율 추출
DISCOUNT_CAR_RATE AS (
    SELECT CAR_TYPE, (1-DISCOUNT_RATE / 100) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
)

SELECT CAR_ID, CAR_TYPE, ROUND(DAILY_FEE * 30 * DISCOUNT_RATE, 0) AS FEE
FROM AVAILABLE_CAR
INNER JOIN DISCOUNT_CAR_RATE USING (CAR_TYPE)
WHERE (DAILY_FEE * 30 * DISCOUNT_RATE >= 500000) AND
(DAILY_FEE * 30 * DISCOUNT_RATE < 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;