# USER_INFO
## USER_ID, GENDER, AGE, JOINED
# ONLINE_SALE
## ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE

SELECT YEAR(S.SALES_DATE) YEAR, MONTH(S.SALES_DATE) MONTH, U.GENDER, COUNT(DISTINCT U.USER_ID) USERS
FROM ONLINE_SALE AS S
JOIN USER_INFO AS U 
ON U.USER_ID = S.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3