SELECT B.WRITER_ID, A.NICKNAME, B.TOTAL_SALES FROM USED_GOODS_USER AS A, (SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES FROM USED_GOODS_BOARD WHERE STATUS = 'DONE' GROUP BY 1 HAVING TOTAL_SALES >= 700000) AS B
WHERE B.WRITER_ID = A.USER_ID 
ORDER BY TOTAL_SALES ASC