# ANIMAL_INS
## ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE
# ANIMAL_OUTS
## ANIMAL_ID, ANIMAL_TYPE, DATETIME, NAME, SEX_UPON_INTAKE
SELECT I.NAME AS NAME, I.DATETIME AS DATETIME FROM ANIMAL_INS AS I
LEFT JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL
ORDER BY I.DATETIME ASC
LIMIT 3;