# BOOK
# AUTHOR
# BOOK_SALES

SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(SALES.SALES * BOOK.PRICE) AS TOTAL_SALES
FROM BOOK_SALES AS SALES
    JOIN BOOK ON BOOK.BOOK_ID = SALES.BOOK_ID
    JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE SALES.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY AUTHOR.AUTHOR_NAME, BOOK.CATEGORY
ORDER BY AUTHOR.AUTHOR_ID, BOOK.CATEGORY desc