# CAR_RENTAL_COMPANY_CAR
# CAR_RENTAL_COMPANY_RENTAL_HISTORY 

SELECT C.CAR_ID FROM CAR_RENTAL_COMPANY_CAR AS C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_ID IN (SELECT H.CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H WHERE START_DATE >= '2022-10-01') AND C.CAR_TYPE = '세단'
GROUP BY 1
ORDER BY 1 DESC