# FIRST_HALF
## SHIPMENT_ID, FALVOR, TOTAL_ORDER
# JULY
## SHIPMENT_ID, FLAVOR, TOTAL_ORDER

SELECT FLAVOR FROM
(SELECT * FROM JULY
UNION ALL
SELECT * FROM FIRST_HALF) AS F
GROUP BY 1
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3
