# PRODUCT
## PRODUCT_ID, PRODUCT_CODE, PRICE
# OFFLINE_SALE
## OFFLINE_SALE_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE

SELECT P.PRODUCT_CODE AS PRODUCT_CODE, SUM(P.PRICE * S.SALES_AMOUNT) AS SALES
FROM PRODUCT AS P
JOIN OFFLINE_SALE AS S
ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;