# BOOK
## BOOK_ID, CATEGORY, AUTHOR_ID, PRICE, PUBLISHED_DATE

# BOOK_SALES
## BOOK_ID, SALES_DATE, SALES

SELECT B.CATEGORY AS CATEGORY, SUM(BS.SALES) AS TOTAL_SALES FROM BOOK_SALES AS BS
JOIN BOOK AS B
ON B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE LIKE "2022-01%"
GROUP BY 1
ORDER BY 1 ASC;